---
title: \...in R
output: html_document
editor_options: 
  chunk_output_type: console
---

# ...in R


## CrossRef API in R

#### By Cyrus Gomes and Vincent Scalfani

Crossref API Documentation: https://api.crossref.org/swagger-ui/index.html

These recipe examples were tested on October 10, 2022.

From our testing, we have found that the crossref metadata across publishers and even journals can vary considerably. As a result, it can be easier to work with one journal at a time when using the crossref API (e.g., particulary when trying to extract selected data from records).

### Setup

Importing the necessary libraries and setting up the base api:


```r
library(tidyverse)  #essential packages
library(purrr)      #character manipulation 
library(httr)       #GET() API requests
library(jsonlite)   #converting to JSON

base_url <- "https://api.crossref.org/works/"
```

### 1. Basic CrossRef API call

#### Let's set up basic parameters


```r
email <- "your_email@ua.edu" #Change this to your email
mailto <- "?mailto="
doi <- "10.1186/1758-2946-4-12" #example

complete_data <- paste(base_url, doi, mailto, email, sep="") #combines it all in one line
complete_data
```

```
## [1] "https://api.crossref.org/works/10.1186/1758-2946-4-12?mailto=your_email@ua.edu"
```

#### Request data from CrossRef


```r
raw_api_data <- GET(complete_data)$content # fetches content from the data
raw_api_data
```

```
##    [1] 7b 22 73 74 61 74 75 73 22 3a 22 6f 6b 22 2c 22 6d 65 73 73 61 67 65 2d
##   [25] 74 79 70 65 22 3a 22 77 6f 72 6b 22 2c 22 6d 65 73 73 61 67 65 2d 76 65
##   [49] 72 73 69 6f 6e 22 3a 22 31 2e 30 2e 30 22 2c 22 6d 65 73 73 61 67 65 22
##   [73] 3a 7b 22 69 6e 64 65 78 65 64 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73
##   [97] 22 3a 5b 5b 32 30 32 33 2c 34 2c 35 5d 5d 2c 22 64 61 74 65 2d 74 69 6d
##  [121] 65 22 3a 22 32 30 32 33 2d 30 34 2d 30 35 54 30 36 3a 35 33 3a 30 38 5a
##  [145] 22 2c 22 74 69 6d 65 73 74 61 6d 70 22 3a 31 36 38 30 36 37 37 35 38 38
##  [169] 36 39 39 7d 2c 22 72 65 66 65 72 65 6e 63 65 2d 63 6f 75 6e 74 22 3a 31
##  [193] 36 2c 22 70 75 62 6c 69 73 68 65 72 22 3a 22 53 70 72 69 6e 67 65 72 20
##  [217] 53 63 69 65 6e 63 65 20 61 6e 64 20 42 75 73 69 6e 65 73 73 20 4d 65 64
##  [241] 69 61 20 4c 4c 43 22 2c 22 69 73 73 75 65 22 3a 22 31 22 2c 22 6c 69 63
##  [265] 65 6e 73 65 22 3a 5b 7b 22 73 74 61 72 74 22 3a 7b 22 64 61 74 65 2d 70
##  [289] 61 72 74 73 22 3a 5b 5b 32 30 31 32 2c 37 2c 36 5d 5d 2c 22 64 61 74 65
##  [313] 2d 74 69 6d 65 22 3a 22 32 30 31 32 2d 30 37 2d 30 36 54 30 30 3a 30 30
##  [337] 3a 30 30 5a 22 2c 22 74 69 6d 65 73 74 61 6d 70 22 3a 31 33 34 31 35 33
##  [361] 32 38 30 30 30 30 30 7d 2c 22 63 6f 6e 74 65 6e 74 2d 76 65 72 73 69 6f
##  [385] 6e 22 3a 22 74 64 6d 22 2c 22 64 65 6c 61 79 2d 69 6e 2d 64 61 79 73 22
##  [409] 3a 30 2c 22 55 52 4c 22 3a 22 68 74 74 70 3a 5c 2f 5c 2f 63 72 65 61 74
##  [433] 69 76 65 63 6f 6d 6d 6f 6e 73 2e 6f 72 67 5c 2f 6c 69 63 65 6e 73 65 73
##  [457] 5c 2f 62 79 5c 2f 32 2e 30 22 7d 5d 2c 22 63 6f 6e 74 65 6e 74 2d 64 6f
##  [481] 6d 61 69 6e 22 3a 7b 22 64 6f 6d 61 69 6e 22 3a 5b 5d 2c 22 63 72 6f 73
##  [505] 73 6d 61 72 6b 2d 72 65 73 74 72 69 63 74 69 6f 6e 22 3a 66 61 6c 73 65
##  [529] 7d 2c 22 73 68 6f 72 74 2d 63 6f 6e 74 61 69 6e 65 72 2d 74 69 74 6c 65
##  [553] 22 3a 5b 22 4a 20 43 68 65 6d 69 6e 66 6f 72 6d 22 5d 2c 22 70 75 62 6c
##  [577] 69 73 68 65 64 2d 70 72 69 6e 74 22 3a 7b 22 64 61 74 65 2d 70 61 72 74
##  [601] 73 22 3a 5b 5b 32 30 31 32 2c 31 32 5d 5d 7d 2c 22 44 4f 49 22 3a 22 31
##  [625] 30 2e 31 31 38 36 5c 2f 31 37 35 38 2d 32 39 34 36 2d 34 2d 31 32 22 2c
##  [649] 22 74 79 70 65 22 3a 22 6a 6f 75 72 6e 61 6c 2d 61 72 74 69 63 6c 65 22
##  [673] 2c 22 63 72 65 61 74 65 64 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73 22
##  [697] 3a 5b 5b 32 30 31 32 2c 37 2c 36 5d 5d 2c 22 64 61 74 65 2d 74 69 6d 65
##  [721] 22 3a 22 32 30 31 32 2d 30 37 2d 30 36 54 31 32 3a 31 34 3a 33 34 5a 22
##  [745] 2c 22 74 69 6d 65 73 74 61 6d 70 22 3a 31 33 34 31 35 37 36 38 37 34 30
##  [769] 30 30 7d 2c 22 73 6f 75 72 63 65 22 3a 22 43 72 6f 73 73 72 65 66 22 2c
##  [793] 22 69 73 2d 72 65 66 65 72 65 6e 63 65 64 2d 62 79 2d 63 6f 75 6e 74 22
##  [817] 3a 33 38 2c 22 74 69 74 6c 65 22 3a 5b 22 54 68 65 20 4d 6f 6c 65 63 75
##  [841] 6c 65 20 43 6c 6f 75 64 20 2d 20 63 6f 6d 70 61 63 74 20 76 69 73 75 61
##  [865] 6c 69 7a 61 74 69 6f 6e 20 6f 66 20 6c 61 72 67 65 20 63 6f 6c 6c 65 63
##  [889] 74 69 6f 6e 73 20 6f 66 20 6d 6f 6c 65 63 75 6c 65 73 22 5d 2c 22 70 72
##  [913] 65 66 69 78 22 3a 22 31 30 2e 31 31 38 36 22 2c 22 76 6f 6c 75 6d 65 22
##  [937] 3a 22 34 22 2c 22 61 75 74 68 6f 72 22 3a 5b 7b 22 67 69 76 65 6e 22 3a
##  [961] 22 50 65 74 65 72 22 2c 22 66 61 6d 69 6c 79 22 3a 22 45 72 74 6c 22 2c
##  [985] 22 73 65 71 75 65 6e 63 65 22 3a 22 66 69 72 73 74 22 2c 22 61 66 66 69
## [1009] 6c 69 61 74 69 6f 6e 22 3a 5b 5d 7d 2c 7b 22 67 69 76 65 6e 22 3a 22 42
## [1033] 65 72 6e 68 61 72 64 22 2c 22 66 61 6d 69 6c 79 22 3a 22 52 6f 68 64 65
## [1057] 22 2c 22 73 65 71 75 65 6e 63 65 22 3a 22 61 64 64 69 74 69 6f 6e 61 6c
## [1081] 22 2c 22 61 66 66 69 6c 69 61 74 69 6f 6e 22 3a 5b 5d 7d 5d 2c 22 6d 65
## [1105] 6d 62 65 72 22 3a 22 32 39 37 22 2c 22 70 75 62 6c 69 73 68 65 64 2d 6f
## [1129] 6e 6c 69 6e 65 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73 22 3a 5b 5b 32
## [1153] 30 31 32 2c 37 2c 36 5d 5d 7d 2c 22 72 65 66 65 72 65 6e 63 65 22 3a 5b
## [1177] 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 31 22 2c 22 64 6f 69 2d 61 73
## [1201] 73 65 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22
## [1225] 66 69 72 73 74 2d 70 61 67 65 22 3a 22 37 37 22 2c 22 44 4f 49 22 3a 22
## [1249] 31 30 2e 31 30 30 37 5c 2f 73 31 30 38 32 32 2d 30 31 31 2d 39 34 38 37
## [1273] 2d 30 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 32 36 22 2c 22 61 75 74 68 6f
## [1297] 72 22 3a 22 45 20 4d 61 72 74 69 6e 22 2c 22 79 65 61 72 22 3a 22 32 30
## [1321] 31 31 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 4d 61 72 74
## [1345] 69 6e 20 45 2c 20 45 72 74 6c 20 50 2c 20 48 75 6e 74 20 50 2c 20 44 75
## [1369] 63 61 20 4a 2c 20 4c 65 77 69 73 20 52 3a 20 47 61 7a 69 6e 67 20 69 6e
## [1393] 74 6f 20 74 68 65 20 63 72 79 73 74 61 6c 20 62 61 6c 6c 3b 20 74 68 65
## [1417] 20 66 75 74 75 72 65 20 6f 66 20 63 6f 6d 70 75 74 65 72 2d 61 69 64 65
## [1441] 64 20 64 72 75 67 20 64 65 73 69 67 6e 2e 20 4a 20 43 6f 6d 70 2d 41 69
## [1465] 64 65 64 20 4d 6f 6c 20 44 65 73 2e 20 32 30 31 31 2c 20 32 36 3a 20 37
## [1489] 37 2d 37 39 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22
## [1513] 4a 20 43 6f 6d 70 2d 41 69 64 65 64 20 4d 6f 6c 20 44 65 73 22 7d 2c 7b
## [1537] 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 32 22 2c 22 64 6f 69 2d 61 73 73
## [1561] 65 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66
## [1585] 69 72 73 74 2d 70 61 67 65 22 3a 22 32 31 37 34 22 2c 22 44 4f 49 22 3a
## [1609] 22 31 30 2e 31 30 32 31 5c 2f 63 69 32 30 30 31 34 32 38 22 2c 22 76 6f
## [1633] 6c 75 6d 65 22 3a 22 32 36 22 2c 22 61 75 74 68 6f 72 22 3a 22 53 52 20
## [1657] 4c 61 6e 67 64 6f 6e 22 2c 22 79 65 61 72 22 3a 22 32 30 31 31 22 2c 22
## [1681] 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 4c 61 6e 67 64 6f 6e 20 53
## [1705] 52 2c 20 42 72 6f 77 6e 20 4e 2c 20 42 6c 61 67 67 20 4a 3a 20 53 63 61
## [1729] 66 66 6f 6c 64 20 64 69 76 65 72 73 69 74 79 20 6f 66 20 65 78 65 6d 70
## [1753] 6c 69 66 69 65 64 20 6d 65 64 69 63 69 6e 61 6c 20 63 68 65 6d 69 73 74
## [1777] 72 79 20 73 70 61 63 65 2e 20 4a 20 43 68 65 6d 20 49 6e 66 20 4d 6f 64
## [1801] 65 6c 2e 20 32 30 31 31 2c 20 32 36 3a 20 32 31 37 34 2d 32 31 38 35 2e
## [1825] 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22 4a 20 43 68 65
## [1849] 6d 20 49 6e 66 20 4d 6f 64 65 6c 22 7d 2c 7b 22 6b 65 79 22 3a 22 33 33
## [1873] 36 5f 43 52 33 22 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64 2d 62 79 22
## [1897] 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d 70 61 67 65
## [1921] 22 3a 22 38 37 33 32 22 2c 22 44 4f 49 22 3a 22 31 30 2e 31 30 32 31 5c
## [1945] 2f 6a 61 39 30 32 33 30 32 68 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 31 33
## [1969] 31 22 2c 22 61 75 74 68 6f 72 22 3a 22 4c 43 20 42 6c 75 6d 22 2c 22 79
## [1993] 65 61 72 22 3a 22 32 30 30 39 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65
## [2017] 64 22 3a 22 42 6c 75 6d 20 4c 43 2c 20 52 65 79 6d 6f 6e 64 20 4a 2d 43
## [2041] 3a 20 39 37 30 20 4d 69 6c 6c 69 6f 6e 20 64 72 75 67 6c 69 6b 65 20 73
## [2065] 6d 61 6c 6c 20 6d 6f 6c 65 63 75 6c 65 73 20 66 6f 72 20 76 69 72 74 75
## [2089] 61 6c 20 73 63 72 65 65 6e 69 6e 67 20 69 6e 20 74 68 65 20 63 68 65 6d
## [2113] 69 63 61 6c 20 75 6e 69 76 65 72 73 65 20 64 61 74 61 62 61 73 65 20 47
## [2137] 44 42 2d 31 33 2e 20 4a 20 41 6d 20 43 68 65 6d 20 53 6f 63 2e 20 32 30
## [2161] 30 39 2c 20 31 33 31 3a 20 38 37 33 32 2d 38 37 33 33 2e 20 31 30 2e 31
## [2185] 30 32 31 5c 2f 6a 61 39 30 32 33 30 32 68 2e 22 2c 22 6a 6f 75 72 6e 61
## [2209] 6c 2d 74 69 74 6c 65 22 3a 22 4a 20 41 6d 20 43 68 65 6d 20 53 6f 63 22
## [2233] 7d 2c 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 34 22 2c 22 64 6f 69 2d
## [2257] 61 73 73 65 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22
## [2281] 2c 22 66 69 72 73 74 2d 70 61 67 65 22 3a 22 31 35 36 22 2c 22 44 4f 49
## [2305] 22 3a 22 31 30 2e 32 31 37 34 5c 2f 31 35 37 33 34 30 39 30 38 37 38 35
## [2329] 37 34 37 34 31 30 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 34 22 2c 22 61 75
## [2353] 74 68 6f 72 22 3a 22 4a 20 44 75 62 6f 69 73 22 2c 22 79 65 61 72 22 3a
## [2377] 22 32 30 30 38 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 44
## [2401] 75 62 6f 69 73 20 4a 2c 20 42 6f 75 72 67 20 53 2c 20 56 72 61 69 6e 20
## [2425] 43 2c 20 4d 6f 72 69 6e 2d 41 6c 6c 6f 72 79 20 4c 3a 20 43 6f 6c 6c 65
## [2449] 63 74 69 6f 6e 73 20 6f 66 20 63 6f 6d 70 6f 75 6e 64 73 20 2d 20 68 6f
## [2473] 77 20 74 6f 20 64 65 61 6c 20 77 69 74 68 20 74 68 65 6d 3f 2e 20 43 75
## [2497] 72 20 43 6f 6d 70 2d 41 69 64 65 64 20 44 72 75 67 20 44 65 73 2e 20 32
## [2521] 30 30 38 2c 20 34 3a 20 31 35 36 2d 31 36 38 2e 20 31 30 2e 32 31 37 34
## [2545] 5c 2f 31 35 37 33 34 30 39 30 38 37 38 35 37 34 37 34 31 30 2e 22 2c 22
## [2569] 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22 43 75 72 20 43 6f 6d 70
## [2593] 2d 41 69 64 65 64 20 44 72 75 67 20 44 65 73 22 7d 2c 7b 22 6b 65 79 22
## [2617] 3a 22 33 33 36 5f 43 52 35 22 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64
## [2641] 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d
## [2665] 70 61 67 65 22 3a 22 33 32 32 22 2c 22 44 4f 49 22 3a 22 31 30 2e 32 31
## [2689] 37 34 5c 2f 31 35 37 33 34 30 39 30 38 37 38 36 37 38 36 30 31 30 22 2c
## [2713] 22 76 6f 6c 75 6d 65 22 3a 22 34 22 2c 22 61 75 74 68 6f 72 22 3a 22 4a
## [2737] 4c 20 4d 65 64 69 6e 61 2d 46 72 61 6e 63 6f 22 2c 22 79 65 61 72 22 3a
## [2761] 22 32 30 30 38 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 4d
## [2785] 65 64 69 6e 61 2d 46 72 61 6e 63 6f 20 4a 4c 2c 20 4d 61 72 74 69 6e 65
## [2809] 7a 2d 4d 61 79 6f 72 67 61 20 4b 2c 20 47 69 75 6c 69 61 6e 6f 74 74 69
## [2833] 20 4d 41 2c 20 48 6f 75 67 68 74 65 6e 20 52 41 2c 20 50 69 6e 69 6c 6c
## [2857] 61 20 43 3a 20 56 69 73 75 61 6c 69 7a 61 74 69 6f 6e 20 6f 66 20 74 68
## [2881] 65 20 63 68 65 6d 69 63 61 6c 20 73 70 61 63 65 20 69 6e 20 64 72 75 67
## [2905] 20 64 69 73 63 6f 76 65 72 79 2e 20 43 75 72 20 43 6f 6d 70 2d 41 69 64
## [2929] 65 64 20 44 72 75 67 20 44 65 73 2e 20 32 30 30 38 2c 20 34 3a 20 33 32
## [2953] 32 2d 33 33 33 2e 20 31 30 2e 32 31 37 34 5c 2f 31 35 37 33 34 30 39 30
## [2977] 38 37 38 36 37 38 36 30 31 30 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69
## [3001] 74 6c 65 22 3a 22 43 75 72 20 43 6f 6d 70 2d 41 69 64 65 64 20 44 72 75
## [3025] 67 20 44 65 73 22 7d 2c 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 36 22
## [3049] 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c
## [3073] 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d 70 61 67 65 22 3a 22 34 37 22
## [3097] 2c 22 44 4f 49 22 3a 22 31 30 2e 31 30 32 31 5c 2f 63 69 36 30 30 33 33
## [3121] 38 78 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 34 37 22 2c 22 61 75 74 68 6f
## [3145] 72 22 3a 22 41 20 53 63 68 75 66 66 65 6e 68 61 75 65 72 22 2c 22 79 65
## [3169] 61 72 22 3a 22 32 30 30 37 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64
## [3193] 22 3a 22 53 63 68 75 66 66 65 6e 68 61 75 65 72 20 41 2c 20 45 72 74 6c
## [3217] 20 50 2c 20 52 6f 67 67 6f 20 53 2c 20 57 65 74 7a 65 6c 20 53 2c 20 4b
## [3241] 6f 63 68 20 4d 41 2c 20 57 61 6c 64 6d 61 6e 6e 20 48 3a 20 54 68 65 20
## [3265] 53 63 61 66 66 6f 6c 64 20 54 72 65 65 20 2d 20 76 69 73 75 61 6c 69 7a
## [3289] 61 74 69 6f 6e 20 6f 66 20 74 68 65 20 73 63 61 66 66 6f 6c 64 20 75 6e
## [3313] 69 76 65 72 73 65 20 62 79 20 68 69 65 72 61 72 63 68 69 63 61 6c 20 73
## [3337] 63 61 66 66 6f 6c 64 20 63 6c 61 73 73 69 66 69 63 61 74 69 6f 6e 2e 20
## [3361] 4a 20 43 68 65 6d 20 49 6e 66 20 4d 6f 64 65 6c 2e 20 32 30 30 37 2c 20
## [3385] 34 37 3a 20 34 37 2d 35 38 2e 20 31 30 2e 31 30 32 31 5c 2f 63 69 36 30
## [3409] 30 33 33 38 78 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a
## [3433] 22 4a 20 43 68 65 6d 20 49 6e 66 20 4d 6f 64 65 6c 22 7d 2c 7b 22 6b 65
## [3457] 79 22 3a 22 33 33 36 5f 43 52 37 22 2c 22 64 6f 69 2d 61 73 73 65 72 74
## [3481] 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73
## [3505] 74 2d 70 61 67 65 22 3a 22 33 36 36 22 2c 22 44 4f 49 22 3a 22 31 30 2e
## [3529] 31 30 30 32 5c 2f 6d 69 6e 66 2e 32 30 31 30 30 30 30 31 39 22 2c 22 76
## [3553] 6f 6c 75 6d 65 22 3a 22 32 39 22 2c 22 61 75 74 68 6f 72 22 3a 22 53 20
## [3577] 4c 61 6e 67 64 6f 6e 22 2c 22 79 65 61 72 22 3a 22 32 30 31 30 22 2c 22
## [3601] 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 4c 61 6e 67 64 6f 6e 20 53
## [3625] 2c 20 45 72 74 6c 20 50 2c 20 42 72 6f 77 6e 20 4e 3a 20 42 69 6f 69 73
## [3649] 6f 73 74 65 72 69 63 20 72 65 70 6c 61 63 65 6d 65 6e 74 20 61 6e 64 20
## [3673] 73 63 61 66 66 6f 6c 64 20 68 6f 70 70 69 6e 67 20 69 6e 20 6c 65 61 64
## [3697] 20 67 65 6e 65 72 61 74 69 6f 6e 20 61 6e 64 20 6f 70 74 69 6d 69 7a 61
## [3721] 74 69 6f 6e 2e 20 4d 6f 6c 20 49 6e 66 2e 20 32 30 31 30 2c 20 32 39 3a
## [3745] 20 33 36 36 2d 33 38 35 2e 20 31 30 2e 31 30 30 32 5c 2f 6d 69 6e 66 2e
## [3769] 32 30 31 30 30 30 30 31 39 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74
## [3793] 6c 65 22 3a 22 4d 6f 6c 20 49 6e 66 22 7d 2c 7b 22 6b 65 79 22 3a 22 33
## [3817] 33 36 5f 43 52 38 22 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64 2d 62 79
## [3841] 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d 70 61 67
## [3865] 65 22 3a 22 34 34 34 33 22 2c 22 44 4f 49 22 3a 22 31 30 2e 31 30 32 31
## [3889] 5c 2f 6a 6f 38 30 30 31 32 37 36 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 37
## [3913] 33 22 2c 22 61 75 74 68 6f 72 22 3a 22 41 48 20 4c 69 70 6b 75 73 22 2c
## [3937] 22 79 65 61 72 22 3a 22 32 30 30 38 22 2c 22 75 6e 73 74 72 75 63 74 75
## [3961] 72 65 64 22 3a 22 4c 69 70 6b 75 73 20 41 48 2c 20 59 75 61 6e 20 51 2c
## [3985] 20 4c 75 63 61 73 20 4b 41 2c 20 46 75 6e 6b 20 53 41 2c 20 42 61 72 74
## [4009] 65 6c 74 20 57 46 2c 20 53 63 68 65 6e 63 6b 20 52 4a 2c 20 54 72 69 70
## [4033] 70 65 20 41 4a 3a 20 53 74 72 75 63 74 75 72 61 6c 20 64 69 76 65 72 73
## [4057] 69 74 79 20 6f 66 20 6f 72 67 61 6e 69 63 20 63 68 65 6d 69 73 74 72 79
## [4081] 2e 20 41 20 73 63 61 66 66 6f 6c 64 20 61 6e 61 6c 79 73 69 73 20 6f 66
## [4105] 20 74 68 65 20 43 41 53 20 52 65 67 69 73 74 72 79 2e 20 4a 20 4f 72 67
## [4129] 20 43 68 65 6d 2e 20 32 30 30 38 2c 20 37 33 3a 20 34 34 34 33 2d 34 34
## [4153] 35 31 2e 20 31 30 2e 31 30 32 31 5c 2f 6a 6f 38 30 30 31 32 37 36 2e 22
## [4177] 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22 4a 20 4f 72 67 20
## [4201] 43 68 65 6d 22 7d 2c 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 39 22 2c
## [4225] 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 6d 69 62 20 32 30 31 30
## [4249] 2e 31 30 2c 20 4d 6f 6c 69 6e 73 70 69 72 61 74 69 6f 6e 20 43 68 65 6d
## [4273] 69 6e 66 6f 72 6d 61 74 69 63 73 3a 20 5c 6e 20 20 20 20 20 20 20 20 20
## [4297] 20 20 20 20 20 20 20 20 20 20 20 68 74 74 70 3a 5c 2f 5c 2f 77 77 77 2e
## [4321] 6d 6f 6c 69 6e 73 70 69 72 61 74 69 6f 6e 2e 63 6f 6d 5c 6e 20 20 20 20
## [4345] 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 5c 6e 20 20 20 20 20 20
## [4369] 20 20 20 20 20 20 20 20 20 20 20 20 2c 22 7d 2c 7b 22 6b 65 79 22 3a 22
## [4393] 33 33 36 5f 43 52 31 30 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22
## [4417] 3a 22 42 65 72 6e 68 61 72 64 20 52 3a 20 41 76 61 6c 6f 6e 20 43 68 65
## [4441] 6d 69 6e 66 6f 72 6d 61 74 69 63 73 20 54 6f 6f 6c 6b 69 74 2e 20 5c 6e
## [4465] 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 68 74 74 70
## [4489] 3a 5c 2f 5c 2f 73 6f 75 72 63 65 66 6f 72 67 65 2e 6e 65 74 5c 2f 70 72
## [4513] 6f 6a 65 63 74 73 5c 2f 61 76 61 6c 6f 6e 74 6f 6f 6c 6b 69 74 5c 2f 5c
## [4537] 6e 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 5c 6e 20
## [4561] 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 2c 22 7d 2c 7b 22 6b
## [4585] 65 79 22 3a 22 33 33 36 5f 43 52 31 31 22 2c 22 64 6f 69 2d 61 73 73 65
## [4609] 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69
## [4633] 72 73 74 2d 70 61 67 65 22 3a 22 44 32 35 35 22 2c 22 44 4f 49 22 3a 22
## [4657] 31 30 2e 31 30 39 33 5c 2f 6e 61 72 5c 2f 67 6b 70 39 36 35 22 2c 22 76
## [4681] 6f 6c 75 6d 65 22 3a 22 33 38 22 2c 22 61 75 74 68 6f 72 22 3a 22 59 20
## [4705] 57 61 6e 67 22 2c 22 79 65 61 72 22 3a 22 32 30 30 39 22 2c 22 75 6e 73
## [4729] 74 72 75 63 74 75 72 65 64 22 3a 22 57 61 6e 67 20 59 2c 20 42 6f 6c 74
## [4753] 6f 6e 20 45 2c 20 44 72 61 63 68 65 76 61 20 53 2c 20 4b 61 72 61 70 65
## [4777] 74 79 61 6e 20 4b 2c 20 53 68 6f 65 6d 61 6b 65 72 20 42 41 2c 20 53 75
## [4801] 7a 65 6b 20 54 4f 2c 20 57 61 6e 67 20 4a 2c 20 58 69 61 6f 20 4a 2c 20
## [4825] 5a 68 61 6e 67 20 4a 2c 20 42 72 79 61 6e 74 20 53 48 3a 20 41 6e 20 6f
## [4849] 76 65 72 76 69 65 77 20 6f 66 20 74 68 65 20 50 75 62 43 68 65 6d 20 42
## [4873] 69 6f 41 73 73 61 79 20 72 65 73 6f 75 72 63 65 2e 20 4e 75 63 6c 65 69
## [4897] 63 20 41 63 69 64 73 20 52 65 73 2e 20 32 30 30 39 2c 20 33 38 3a 20 44
## [4921] 32 35 35 2d 44 32 36 36 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c
## [4945] 65 22 3a 22 4e 75 63 6c 65 69 63 20 41 63 69 64 73 20 52 65 73 22 7d 2c
## [4969] 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 31 32 22 2c 22 64 6f 69 2d 61
## [4993] 73 73 65 72 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c
## [5017] 22 66 69 72 73 74 2d 70 61 67 65 22 3a 22 31 37 37 22 2c 22 44 4f 49 22
## [5041] 3a 22 31 30 2e 31 30 32 31 5c 2f 63 69 30 34 39 37 31 34 2b 22 2c 22 76
## [5065] 6f 6c 75 6d 65 22 3a 22 34 35 22 2c 22 61 75 74 68 6f 72 22 3a 22 4a 4a
## [5089] 20 49 72 77 69 6e 22 2c 22 79 65 61 72 22 3a 22 32 30 30 34 22 2c 22 75
## [5113] 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 49 72 77 69 6e 20 4a 4a 2c 20
## [5137] 53 68 6f 69 63 68 65 74 20 42 4b 3a 20 5a 49 4e 43 5c 75 32 30 30 39 5c
## [5161] 75 32 32 31 32 5c 75 32 30 30 39 61 20 66 72 65 65 20 64 61 74 61 62 61
## [5185] 73 65 20 6f 66 20 63 6f 6d 6d 65 72 63 69 61 6c 6c 79 20 61 76 61 69 6c
## [5209] 61 62 6c 65 20 63 6f 6d 70 6f 75 6e 64 73 20 66 6f 72 20 76 69 72 74 75
## [5233] 61 6c 20 73 63 72 65 65 6e 69 6e 67 2e 20 4a 20 43 68 65 6d 20 49 6e 66
## [5257] 20 4d 6f 64 65 6c 2e 20 32 30 30 34 2c 20 34 35 3a 20 31 37 37 2d 31 38
## [5281] 32 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22 4a 20 43
## [5305] 68 65 6d 20 49 6e 66 20 4d 6f 64 65 6c 22 7d 2c 7b 22 6b 65 79 22 3a 22
## [5329] 33 33 36 5f 43 52 31 33 22 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64 2d
## [5353] 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d 70
## [5377] 61 67 65 22 3a 22 44 31 31 30 30 22 2c 22 44 4f 49 22 3a 22 31 30 2e 31
## [5401] 30 39 33 5c 2f 6e 61 72 5c 2f 67 6b 72 37 37 37 22 2c 22 76 6f 6c 75 6d
## [5425] 65 22 3a 22 34 30 22 2c 22 61 75 74 68 6f 72 22 3a 22 41 20 47 61 75 6c
## [5449] 74 6f 6e 22 2c 22 79 65 61 72 22 3a 22 32 30 31 32 22 2c 22 75 6e 73 74
## [5473] 72 75 63 74 75 72 65 64 22 3a 22 47 61 75 6c 74 6f 6e 20 41 2c 20 42 65
## [5497] 6c 6c 69 73 20 4c 4a 2c 20 42 65 6e 74 6f 20 41 50 2c 20 43 68 61 6d 62
## [5521] 65 72 73 20 4a 2c 20 44 61 76 69 65 73 20 4d 2c 20 48 65 72 73 65 79 20
## [5545] 41 2c 20 4c 69 67 68 74 20 59 2c 20 4d 63 47 6c 69 6e 63 68 65 79 20 53
## [5569] 2c 20 4d 69 63 68 61 6c 6f 76 69 63 68 20 44 2c 20 41 6c 2d 4c 61 7a 69
## [5593] 6b 61 6e 69 20 42 2c 20 4f 76 65 72 69 6e 67 74 6f 6e 20 4a 50 3a 20 43
## [5617] 68 45 4d 42 4c 3a 20 61 20 6c 61 72 67 65 2d 73 63 61 6c 65 20 62 69 6f
## [5641] 61 63 74 69 76 69 74 79 20 64 61 74 61 62 61 73 65 20 66 6f 72 20 64 72
## [5665] 75 67 20 64 69 73 63 6f 76 65 72 79 2e 20 4e 75 63 6c 65 69 63 20 41 63
## [5689] 69 64 73 20 52 65 73 2e 20 32 30 31 32 2c 20 34 30 3a 20 44 31 31 30 30
## [5713] 2d 44 31 31 30 37 2e 20 31 30 2e 31 30 39 33 5c 2f 6e 61 72 5c 2f 67 6b
## [5737] 72 37 37 37 2e 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22
## [5761] 4e 75 63 6c 65 69 63 20 41 63 69 64 73 20 52 65 73 22 7d 2c 7b 22 6b 65
## [5785] 79 22 3a 22 33 33 36 5f 43 52 31 34 22 2c 22 64 6f 69 2d 61 73 73 65 72
## [5809] 74 65 64 2d 62 79 22 3a 22 70 75 62 6c 69 73 68 65 72 22 2c 22 66 69 72
## [5833] 73 74 2d 70 61 67 65 22 3a 22 33 34 37 22 2c 22 44 4f 49 22 3a 22 31 30
## [5857] 2e 31 30 31 36 5c 2f 6a 2e 63 62 70 61 2e 32 30 31 30 2e 30 32 2e 30 31
## [5881] 38 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 31 34 22 2c 22 61 75 74 68 6f 72
## [5905] 22 3a 22 4d 45 20 57 65 6c 73 63 68 22 2c 22 79 65 61 72 22 3a 22 32 30
## [5929] 31 30 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 57 65 6c 73
## [5953] 63 68 20 4d 45 2c 20 53 6e 79 64 65 72 20 53 41 2c 20 53 74 6f 63 6b 77
## [5977] 65 6c 6c 20 42 52 3a 20 50 72 69 76 69 6c 65 67 65 64 20 73 63 61 66 66
## [6001] 6f 6c 64 73 20 66 6f 72 20 6c 69 62 72 61 72 79 20 64 65 73 69 67 6e 20
## [6025] 61 6e 64 20 64 72 75 67 20 64 69 73 63 6f 76 65 72 79 2e 20 43 75 72 72
## [6049] 20 4f 70 69 6e 20 43 68 65 6d 20 42 69 6f 6c 2e 20 32 30 31 30 2c 20 31
## [6073] 34 3a 20 33 34 37 2d 33 36 31 2e 20 31 30 2e 31 30 31 36 5c 2f 6a 2e 63
## [6097] 62 70 61 2e 32 30 31 30 2e 30 32 2e 30 31 38 2e 22 2c 22 6a 6f 75 72 6e
## [6121] 61 6c 2d 74 69 74 6c 65 22 3a 22 43 75 72 72 20 4f 70 69 6e 20 43 68 65
## [6145] 6d 20 42 69 6f 6c 22 7d 2c 7b 22 6b 65 79 22 3a 22 33 33 36 5f 43 52 31
## [6169] 35 22 2c 22 64 6f 69 2d 61 73 73 65 72 74 65 64 2d 62 79 22 3a 22 70 75
## [6193] 62 6c 69 73 68 65 72 22 2c 22 66 69 72 73 74 2d 70 61 67 65 22 3a 22 33
## [6217] 37 34 22 2c 22 44 4f 49 22 3a 22 31 30 2e 31 30 32 31 5c 2f 63 69 30 32
## [6241] 35 35 37 38 32 22 2c 22 76 6f 6c 75 6d 65 22 3a 22 34 33 22 2c 22 61 75
## [6265] 74 68 6f 72 22 3a 22 50 20 45 72 74 6c 22 2c 22 79 65 61 72 22 3a 22 32
## [6289] 30 30 33 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64 22 3a 22 45 72 74
## [6313] 6c 20 50 3a 20 43 68 65 6d 69 6e 66 6f 72 6d 61 74 69 63 73 20 61 6e 61
## [6337] 6c 79 73 69 73 20 6f 66 20 6f 72 67 61 6e 69 63 20 73 75 62 73 74 69 74
## [6361] 75 65 6e 74 73 3a 20 49 64 65 6e 74 69 66 69 63 61 74 69 6f 6e 20 6f 66
## [6385] 20 74 68 65 20 6d 6f 73 74 20 63 6f 6d 6d 6f 6e 20 73 75 62 73 74 69 74
## [6409] 75 65 6e 74 73 2c 20 63 61 6c 63 75 6c 61 74 69 6f 6e 20 6f 66 20 73 75
## [6433] 62 73 74 69 74 75 65 6e 74 20 70 72 6f 70 65 72 74 69 65 73 2c 20 61 6e
## [6457] 64 20 61 75 74 6f 6d 61 74 69 63 20 69 64 65 6e 74 69 66 69 63 61 74 69
## [6481] 6f 6e 20 6f 66 20 64 72 75 67 2d 6c 69 6b 65 20 62 69 6f 69 73 6f 73 74
## [6505] 65 72 69 63 20 67 72 6f 75 70 73 2e 20 4a 20 43 68 65 6d 20 49 6e 66 20
## [6529] 43 6f 6d 70 20 53 63 69 2e 20 32 30 30 33 2c 20 34 33 3a 20 33 37 34 2d
## [6553] 33 38 30 2e 20 31 30 2e 31 30 32 31 5c 2f 63 69 30 32 35 35 37 38 32 2e
## [6577] 22 2c 22 6a 6f 75 72 6e 61 6c 2d 74 69 74 6c 65 22 3a 22 4a 20 43 68 65
## [6601] 6d 20 49 6e 66 20 43 6f 6d 70 20 53 63 69 22 7d 2c 7b 22 6b 65 79 22 3a
## [6625] 22 33 33 36 5f 43 52 31 36 22 2c 22 75 6e 73 74 72 75 63 74 75 72 65 64
## [6649] 22 3a 22 54 61 67 43 72 6f 77 64 3a 20 5c 6e 20 20 20 20 20 20 20 20 20
## [6673] 20 20 20 20 20 20 20 20 20 20 20 68 74 74 70 3a 5c 2f 5c 2f 74 61 67 63
## [6697] 72 6f 77 64 2e 63 6f 6d 22 7d 5d 2c 22 63 6f 6e 74 61 69 6e 65 72 2d 74
## [6721] 69 74 6c 65 22 3a 5b 22 4a 6f 75 72 6e 61 6c 20 6f 66 20 43 68 65 6d 69
## [6745] 6e 66 6f 72 6d 61 74 69 63 73 22 5d 2c 22 6f 72 69 67 69 6e 61 6c 2d 74
## [6769] 69 74 6c 65 22 3a 5b 5d 2c 22 6c 61 6e 67 75 61 67 65 22 3a 22 65 6e 22
## [6793] 2c 22 6c 69 6e 6b 22 3a 5b 7b 22 55 52 4c 22 3a 22 68 74 74 70 3a 5c 2f
## [6817] 5c 2f 6c 69 6e 6b 2e 73 70 72 69 6e 67 65 72 2e 63 6f 6d 5c 2f 63 6f 6e
## [6841] 74 65 6e 74 5c 2f 70 64 66 5c 2f 31 30 2e 31 31 38 36 5c 2f 31 37 35 38
## [6865] 2d 32 39 34 36 2d 34 2d 31 32 2e 70 64 66 22 2c 22 63 6f 6e 74 65 6e 74
## [6889] 2d 74 79 70 65 22 3a 22 61 70 70 6c 69 63 61 74 69 6f 6e 5c 2f 70 64 66
## [6913] 22 2c 22 63 6f 6e 74 65 6e 74 2d 76 65 72 73 69 6f 6e 22 3a 22 76 6f 72
## [6937] 22 2c 22 69 6e 74 65 6e 64 65 64 2d 61 70 70 6c 69 63 61 74 69 6f 6e 22
## [6961] 3a 22 74 65 78 74 2d 6d 69 6e 69 6e 67 22 7d 2c 7b 22 55 52 4c 22 3a 22
## [6985] 68 74 74 70 3a 5c 2f 5c 2f 6c 69 6e 6b 2e 73 70 72 69 6e 67 65 72 2e 63
## [7009] 6f 6d 5c 2f 61 72 74 69 63 6c 65 5c 2f 31 30 2e 31 31 38 36 5c 2f 31 37
## [7033] 35 38 2d 32 39 34 36 2d 34 2d 31 32 5c 2f 66 75 6c 6c 74 65 78 74 2e 68
## [7057] 74 6d 6c 22 2c 22 63 6f 6e 74 65 6e 74 2d 74 79 70 65 22 3a 22 74 65 78
## [7081] 74 5c 2f 68 74 6d 6c 22 2c 22 63 6f 6e 74 65 6e 74 2d 76 65 72 73 69 6f
## [7105] 6e 22 3a 22 76 6f 72 22 2c 22 69 6e 74 65 6e 64 65 64 2d 61 70 70 6c 69
## [7129] 63 61 74 69 6f 6e 22 3a 22 74 65 78 74 2d 6d 69 6e 69 6e 67 22 7d 2c 7b
## [7153] 22 55 52 4c 22 3a 22 68 74 74 70 3a 5c 2f 5c 2f 6c 69 6e 6b 2e 73 70 72
## [7177] 69 6e 67 65 72 2e 63 6f 6d 5c 2f 63 6f 6e 74 65 6e 74 5c 2f 70 64 66 5c
## [7201] 2f 31 30 2e 31 31 38 36 5c 2f 31 37 35 38 2d 32 39 34 36 2d 34 2d 31 32
## [7225] 2e 70 64 66 22 2c 22 63 6f 6e 74 65 6e 74 2d 74 79 70 65 22 3a 22 61 70
## [7249] 70 6c 69 63 61 74 69 6f 6e 5c 2f 70 64 66 22 2c 22 63 6f 6e 74 65 6e 74
## [7273] 2d 76 65 72 73 69 6f 6e 22 3a 22 76 6f 72 22 2c 22 69 6e 74 65 6e 64 65
## [7297] 64 2d 61 70 70 6c 69 63 61 74 69 6f 6e 22 3a 22 73 69 6d 69 6c 61 72 69
## [7321] 74 79 2d 63 68 65 63 6b 69 6e 67 22 7d 5d 2c 22 64 65 70 6f 73 69 74 65
## [7345] 64 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73 22 3a 5b 5b 32 30 31 39 2c
## [7369] 36 2c 32 34 5d 5d 2c 22 64 61 74 65 2d 74 69 6d 65 22 3a 22 32 30 31 39
## [7393] 2d 30 36 2d 32 34 54 31 34 3a 32 32 3a 30 37 5a 22 2c 22 74 69 6d 65 73
## [7417] 74 61 6d 70 22 3a 31 35 36 31 33 38 36 31 32 37 30 30 30 7d 2c 22 73 63
## [7441] 6f 72 65 22 3a 31 2c 22 72 65 73 6f 75 72 63 65 22 3a 7b 22 70 72 69 6d
## [7465] 61 72 79 22 3a 7b 22 55 52 4c 22 3a 22 68 74 74 70 73 3a 5c 2f 5c 2f 6a
## [7489] 63 68 65 6d 69 6e 66 2e 62 69 6f 6d 65 64 63 65 6e 74 72 61 6c 2e 63 6f
## [7513] 6d 5c 2f 61 72 74 69 63 6c 65 73 5c 2f 31 30 2e 31 31 38 36 5c 2f 31 37
## [7537] 35 38 2d 32 39 34 36 2d 34 2d 31 32 22 7d 7d 2c 22 73 75 62 74 69 74 6c
## [7561] 65 22 3a 5b 5d 2c 22 73 68 6f 72 74 2d 74 69 74 6c 65 22 3a 5b 5d 2c 22
## [7585] 69 73 73 75 65 64 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73 22 3a 5b 5b
## [7609] 32 30 31 32 2c 37 2c 36 5d 5d 7d 2c 22 72 65 66 65 72 65 6e 63 65 73 2d
## [7633] 63 6f 75 6e 74 22 3a 31 36 2c 22 6a 6f 75 72 6e 61 6c 2d 69 73 73 75 65
## [7657] 22 3a 7b 22 69 73 73 75 65 22 3a 22 31 22 2c 22 70 75 62 6c 69 73 68 65
## [7681] 64 2d 70 72 69 6e 74 22 3a 7b 22 64 61 74 65 2d 70 61 72 74 73 22 3a 5b
## [7705] 5b 32 30 31 32 2c 31 32 5d 5d 7d 7d 2c 22 61 6c 74 65 72 6e 61 74 69 76
## [7729] 65 2d 69 64 22 3a 5b 22 33 33 36 22 5d 2c 22 55 52 4c 22 3a 22 68 74 74
## [7753] 70 3a 5c 2f 5c 2f 64 78 2e 64 6f 69 2e 6f 72 67 5c 2f 31 30 2e 31 31 38
## [7777] 36 5c 2f 31 37 35 38 2d 32 39 34 36 2d 34 2d 31 32 22 2c 22 72 65 6c 61
## [7801] 74 69 6f 6e 22 3a 7b 7d 2c 22 49 53 53 4e 22 3a 5b 22 31 37 35 38 2d 32
## [7825] 39 34 36 22 5d 2c 22 69 73 73 6e 2d 74 79 70 65 22 3a 5b 7b 22 76 61 6c
## [7849] 75 65 22 3a 22 31 37 35 38 2d 32 39 34 36 22 2c 22 74 79 70 65 22 3a 22
## [7873] 65 6c 65 63 74 72 6f 6e 69 63 22 7d 5d 2c 22 73 75 62 6a 65 63 74 22 3a
## [7897] 5b 22 4c 69 62 72 61 72 79 20 61 6e 64 20 49 6e 66 6f 72 6d 61 74 69 6f
## [7921] 6e 20 53 63 69 65 6e 63 65 73 22 2c 22 43 6f 6d 70 75 74 65 72 20 47 72
## [7945] 61 70 68 69 63 73 20 61 6e 64 20 43 6f 6d 70 75 74 65 72 2d 41 69 64 65
## [7969] 64 20 44 65 73 69 67 6e 22 2c 22 50 68 79 73 69 63 61 6c 20 61 6e 64 20
## [7993] 54 68 65 6f 72 65 74 69 63 61 6c 20 43 68 65 6d 69 73 74 72 79 22 2c 22
## [8017] 43 6f 6d 70 75 74 65 72 20 53 63 69 65 6e 63 65 20 41 70 70 6c 69 63 61
## [8041] 74 69 6f 6e 73 22 5d 2c 22 70 75 62 6c 69 73 68 65 64 22 3a 7b 22 64 61
## [8065] 74 65 2d 70 61 72 74 73 22 3a 5b 5b 32 30 31 32 2c 37 2c 36 5d 5d 7d 2c
## [8089] 22 61 72 74 69 63 6c 65 2d 6e 75 6d 62 65 72 22 3a 22 31 32 22 7d 7d
```
The raw data is in hexadecimal and is hard to read.

#### Converting the data to JSON format (which is more readable)


```r
api_data <- fromJSON(rawToChar(raw_api_data), flatten = TRUE)
print(api_data)
```

```
## $status
## [1] "ok"
## 
## $`message-type`
## [1] "work"
## 
## $`message-version`
## [1] "1.0.0"
## 
## $message
## $message$indexed
## $message$indexed$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2023    4    5
## 
## $message$indexed$`date-time`
## [1] "2023-04-05T06:53:08Z"
## 
## $message$indexed$timestamp
## [1] 1.680678e+12
## 
## 
## $message$`reference-count`
## [1] 16
## 
## $message$publisher
## [1] "Springer Science and Business Media LLC"
## 
## $message$issue
## [1] "1"
## 
## $message$license
##   content-version delay-in-days                                        URL
## 1             tdm             0 http://creativecommons.org/licenses/by/2.0
##   start.date-parts      start.date-time start.timestamp
## 1       2012, 7, 6 2012-07-06T00:00:00Z    1.341533e+12
## 
## $message$`content-domain`
## $message$`content-domain`$domain
## list()
## 
## $message$`content-domain`$`crossmark-restriction`
## [1] FALSE
## 
## 
## $message$`short-container-title`
## [1] "J Cheminform"
## 
## $message$`published-print`
## $message$`published-print`$`date-parts`
##      [,1] [,2]
## [1,] 2012   12
## 
## 
## $message$DOI
## [1] "10.1186/1758-2946-4-12"
## 
## $message$type
## [1] "journal-article"
## 
## $message$created
## $message$created$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## $message$created$`date-time`
## [1] "2012-07-06T12:14:34Z"
## 
## $message$created$timestamp
## [1] 1.341577e+12
## 
## 
## $message$source
## [1] "Crossref"
## 
## $message$`is-referenced-by-count`
## [1] 38
## 
## $message$title
## [1] "The Molecule Cloud - compact visualization of large collections of molecules"
## 
## $message$prefix
## [1] "10.1186"
## 
## $message$volume
## [1] "4"
## 
## $message$author
##      given family   sequence affiliation
## 1    Peter   Ertl      first        NULL
## 2 Bernhard  Rohde additional        NULL
## 
## $message$member
## [1] "297"
## 
## $message$`published-online`
## $message$`published-online`$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$reference
##         key doi-asserted-by first-page                        DOI volume
## 1   336_CR1       publisher         77  10.1007/s10822-011-9487-0     26
## 2   336_CR2       publisher       2174          10.1021/ci2001428     26
## 3   336_CR3       publisher       8732          10.1021/ja902302h    131
## 4   336_CR4       publisher        156 10.2174/157340908785747410      4
## 5   336_CR5       publisher        322 10.2174/157340908786786010      4
## 6   336_CR6       publisher         47          10.1021/ci600338x     47
## 7   336_CR7       publisher        366     10.1002/minf.201000019     29
## 8   336_CR8       publisher       4443          10.1021/jo8001276     73
## 9   336_CR9            <NA>       <NA>                       <NA>   <NA>
## 10 336_CR10            <NA>       <NA>                       <NA>   <NA>
## 11 336_CR11       publisher       D255         10.1093/nar/gkp965     38
## 12 336_CR12       publisher        177          10.1021/ci049714+     45
## 13 336_CR13       publisher      D1100         10.1093/nar/gkr777     40
## 14 336_CR14       publisher        347 10.1016/j.cbpa.2010.02.018     14
## 15 336_CR15       publisher        374          10.1021/ci0255782     43
## 16 336_CR16            <NA>       <NA>                       <NA>   <NA>
##              author year
## 1          E Martin 2011
## 2        SR Langdon 2011
## 3           LC Blum 2009
## 4          J Dubois 2008
## 5  JL Medina-Franco 2008
## 6   A Schuffenhauer 2007
## 7         S Langdon 2010
## 8         AH Lipkus 2008
## 9              <NA> <NA>
## 10             <NA> <NA>
## 11           Y Wang 2009
## 12         JJ Irwin 2004
## 13        A Gaulton 2012
## 14        ME Welsch 2010
## 15           P Ertl 2003
## 16             <NA> <NA>
##                                                                                                                                                                                                                                                                  unstructured
## 1                                                                                                                   Martin E, Ertl P, Hunt P, Duca J, Lewis R: Gazing into the crystal ball; the future of computer-aided drug design. J Comp-Aided Mol Des. 2011, 26: 77-79.
## 2                                                                                                                                           Langdon SR, Brown N, Blagg J: Scaffold diversity of exemplified medicinal chemistry space. J Chem Inf Model. 2011, 26: 2174-2185.
## 3                                                                                          Blum LC, Reymond J-C: 970 Million druglike small molecules for virtual screening in the chemical universe database GDB-13. J Am Chem Soc. 2009, 131: 8732-8733. 10.1021/ja902302h.
## 4                                                                                                       Dubois J, Bourg S, Vrain C, Morin-Allory L: Collections of compounds - how to deal with them?. Cur Comp-Aided Drug Des. 2008, 4: 156-168. 10.2174/157340908785747410.
## 5                                                                 Medina-Franco JL, Martinez-Mayorga K, Giulianotti MA, Houghten RA, Pinilla C: Visualization of the chemical space in drug discovery. Cur Comp-Aided Drug Des. 2008, 4: 322-333. 10.2174/157340908786786010.
## 6                                                  Schuffenhauer A, Ertl P, Roggo S, Wetzel S, Koch MA, Waldmann H: The Scaffold Tree - visualization of the scaffold universe by hierarchical scaffold classification. J Chem Inf Model. 2007, 47: 47-58. 10.1021/ci600338x.
## 7                                                                                                          Langdon S, Ertl P, Brown N: Bioisosteric replacement and scaffold hopping in lead generation and optimization. Mol Inf. 2010, 29: 366-385. 10.1002/minf.201000019.
## 8                                                            Lipkus AH, Yuan Q, Lucas KA, Funk SA, Bartelt WF, Schenck RJ, Trippe AJ: Structural diversity of organic chemistry. A scaffold analysis of the CAS Registry. J Org Chem. 2008, 73: 4443-4451. 10.1021/jo8001276.
## 9                                                                                                                                 mib 2010.10, Molinspiration Cheminformatics: \n                    http://www.molinspiration.com\n                    \n                  ,
## 10                                                                                                                Bernhard R: Avalon Cheminformatics Toolkit. \n                    http://sourceforge.net/projects/avalontoolkit/\n                    \n                  ,
## 11                                                                              Wang Y, Bolton E, Dracheva S, Karapetyan K, Shoemaker BA, Suzek TO, Wang J, Xiao J, Zhang J, Bryant SH: An overview of the PubChem BioAssay resource. Nucleic Acids Res. 2009, 38: D255-D266.
## 12                                                                                                                              Irwin JJ, Shoichet BK: ZINC − a free database of commercially available compounds for virtual screening. J Chem Inf Model. 2004, 45: 177-182.
## 13           Gaulton A, Bellis LJ, Bento AP, Chambers J, Davies M, Hersey A, Light Y, McGlinchey S, Michalovich D, Al-Lazikani B, Overington JP: ChEMBL: a large-scale bioactivity database for drug discovery. Nucleic Acids Res. 2012, 40: D1100-D1107. 10.1093/nar/gkr777.
## 14                                                                                                        Welsch ME, Snyder SA, Stockwell BR: Privileged scaffolds for library design and drug discovery. Curr Opin Chem Biol. 2010, 14: 347-361. 10.1016/j.cbpa.2010.02.018.
## 15 Ertl P: Cheminformatics analysis of organic substituents: Identification of the most common substituents, calculation of substituent properties, and automatic identification of drug-like bioisosteric groups. J Chem Inf Comp Sci. 2003, 43: 374-380. 10.1021/ci0255782.
## 16                                                                                                                                                                                                                        TagCrowd: \n                    http://tagcrowd.com
##              journal-title
## 1     J Comp-Aided Mol Des
## 2         J Chem Inf Model
## 3            J Am Chem Soc
## 4  Cur Comp-Aided Drug Des
## 5  Cur Comp-Aided Drug Des
## 6         J Chem Inf Model
## 7                  Mol Inf
## 8               J Org Chem
## 9                     <NA>
## 10                    <NA>
## 11       Nucleic Acids Res
## 12        J Chem Inf Model
## 13       Nucleic Acids Res
## 14     Curr Opin Chem Biol
## 15     J Chem Inf Comp Sci
## 16                    <NA>
## 
## $message$`container-title`
## [1] "Journal of Cheminformatics"
## 
## $message$`original-title`
## list()
## 
## $message$language
## [1] "en"
## 
## $message$link
##                                                                     URL
## 1       http://link.springer.com/content/pdf/10.1186/1758-2946-4-12.pdf
## 2 http://link.springer.com/article/10.1186/1758-2946-4-12/fulltext.html
## 3       http://link.springer.com/content/pdf/10.1186/1758-2946-4-12.pdf
##      content-type content-version intended-application
## 1 application/pdf             vor          text-mining
## 2       text/html             vor          text-mining
## 3 application/pdf             vor  similarity-checking
## 
## $message$deposited
## $message$deposited$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2019    6   24
## 
## $message$deposited$`date-time`
## [1] "2019-06-24T14:22:07Z"
## 
## $message$deposited$timestamp
## [1] 1.561386e+12
## 
## 
## $message$score
## [1] 1
## 
## $message$resource
## $message$resource$primary
## $message$resource$primary$URL
## [1] "https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-4-12"
## 
## 
## 
## $message$subtitle
## list()
## 
## $message$`short-title`
## list()
## 
## $message$issued
## $message$issued$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$`references-count`
## [1] 16
## 
## $message$`journal-issue`
## $message$`journal-issue`$issue
## [1] "1"
## 
## $message$`journal-issue`$`published-print`
## $message$`journal-issue`$`published-print`$`date-parts`
##      [,1] [,2]
## [1,] 2012   12
## 
## 
## 
## $message$`alternative-id`
## [1] "336"
## 
## $message$URL
## [1] "http://dx.doi.org/10.1186/1758-2946-4-12"
## 
## $message$relation
## named list()
## 
## $message$ISSN
## [1] "1758-2946"
## 
## $message$`issn-type`
##       value       type
## 1 1758-2946 electronic
## 
## $message$subject
## [1] "Library and Information Sciences"           
## [2] "Computer Graphics and Computer-Aided Design"
## [3] "Physical and Theoretical Chemistry"         
## [4] "Computer Science Applications"              
## 
## $message$published
## $message$published$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$`article-number`
## [1] "12"
```

Replace the above DOI value with a different DOI to customize.

#### Let's see the reference part of CrossRef in a convenient tabular way


```r
api_data$message$`reference`[1:7,1:7]    # prints the table of data
```

```
##       key doi-asserted-by first-page                        DOI volume
## 1 336_CR1       publisher         77  10.1007/s10822-011-9487-0     26
## 2 336_CR2       publisher       2174          10.1021/ci2001428     26
## 3 336_CR3       publisher       8732          10.1021/ja902302h    131
## 4 336_CR4       publisher        156 10.2174/157340908785747410      4
## 5 336_CR5       publisher        322 10.2174/157340908786786010      4
## 6 336_CR6       publisher         47          10.1021/ci600338x     47
## 7 336_CR7       publisher        366     10.1002/minf.201000019     29
##             author year
## 1         E Martin 2011
## 2       SR Langdon 2011
## 3          LC Blum 2009
## 4         J Dubois 2008
## 5 JL Medina-Franco 2008
## 6  A Schuffenhauer 2007
## 7        S Langdon 2010
```

#### Selecting some specific data

Getting the Journal Title


```r
#Get Journal Title
api_data$message$`container-title` # prints the title
```

```
## [1] "Journal of Cheminformatics"
```

Getting the Article Title


```r
api_data$message$`title` 
```

```
## [1] "The Molecule Cloud - compact visualization of large collections of molecules"
```

Getting the Article Author Names


```r
for (au in api_data$message$author){
  article_authors <- paste(api_data$message$author$given, api_data$message$author$family)
}
article_authors
```

```
## [1] "Peter Ertl"     "Bernhard Rohde"
```

Getting the Bibliography References and saving them to a list


```r
#Get bibliography references and save to list
bib_refs <- list()  #declare a list
for (ref in api_data$message$reference){
  bib_refs <- append(x = bib_refs, api_data$message$reference$unstructured)
}
bib_refs[0:5]
```

```
## [[1]]
## [1] "Martin E, Ertl P, Hunt P, Duca J, Lewis R: Gazing into the crystal ball; the future of computer-aided drug design. J Comp-Aided Mol Des. 2011, 26: 77-79."
## 
## [[2]]
## [1] "Langdon SR, Brown N, Blagg J: Scaffold diversity of exemplified medicinal chemistry space. J Chem Inf Model. 2011, 26: 2174-2185."
## 
## [[3]]
## [1] "Blum LC, Reymond J-C: 970 Million druglike small molecules for virtual screening in the chemical universe database GDB-13. J Am Chem Soc. 2009, 131: 8732-8733. 10.1021/ja902302h."
## 
## [[4]]
## [1] "Dubois J, Bourg S, Vrain C, Morin-Allory L: Collections of compounds - how to deal with them?. Cur Comp-Aided Drug Des. 2008, 4: 156-168. 10.2174/157340908785747410."
## 
## [[5]]
## [1] "Medina-Franco JL, Martinez-Mayorga K, Giulianotti MA, Houghten RA, Pinilla C: Visualization of the chemical space in drug discovery. Cur Comp-Aided Drug Des. 2008, 4: 322-333. 10.2174/157340908786786010."
```

#### Save JSON data to a file

This is particularly useful for downstream testing or returning to results in the future (e.g., no need to keep requesting the data from crossref, save the results to a file)


```r
#Save JSON data to a file
jsonData <- toJSON(api_data)
write (jsonData, "output.json")
```

#### Load JSON data from a file


```r
loaded_data <- fromJSON("output.json")
loaded_data                       #Load Json data from file 
```

```
## $status
## [1] "ok"
## 
## $`message-type`
## [1] "work"
## 
## $`message-version`
## [1] "1.0.0"
## 
## $message
## $message$indexed
## $message$indexed$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2023    4    5
## 
## $message$indexed$`date-time`
## [1] "2023-04-05T06:53:08Z"
## 
## $message$indexed$timestamp
## [1] 1.680678e+12
## 
## 
## $message$`reference-count`
## [1] 16
## 
## $message$publisher
## [1] "Springer Science and Business Media LLC"
## 
## $message$issue
## [1] "1"
## 
## $message$license
##   content-version delay-in-days                                        URL
## 1             tdm             0 http://creativecommons.org/licenses/by/2.0
##   start.date-parts      start.date-time start.timestamp
## 1       2012, 7, 6 2012-07-06T00:00:00Z    1.341533e+12
## 
## $message$`content-domain`
## $message$`content-domain`$domain
## list()
## 
## $message$`content-domain`$`crossmark-restriction`
## [1] FALSE
## 
## 
## $message$`short-container-title`
## [1] "J Cheminform"
## 
## $message$`published-print`
## $message$`published-print`$`date-parts`
##      [,1] [,2]
## [1,] 2012   12
## 
## 
## $message$DOI
## [1] "10.1186/1758-2946-4-12"
## 
## $message$type
## [1] "journal-article"
## 
## $message$created
## $message$created$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## $message$created$`date-time`
## [1] "2012-07-06T12:14:34Z"
## 
## $message$created$timestamp
## [1] 1.341577e+12
## 
## 
## $message$source
## [1] "Crossref"
## 
## $message$`is-referenced-by-count`
## [1] 38
## 
## $message$title
## [1] "The Molecule Cloud - compact visualization of large collections of molecules"
## 
## $message$prefix
## [1] "10.1186"
## 
## $message$volume
## [1] "4"
## 
## $message$author
##      given family   sequence affiliation
## 1    Peter   Ertl      first        NULL
## 2 Bernhard  Rohde additional        NULL
## 
## $message$member
## [1] "297"
## 
## $message$`published-online`
## $message$`published-online`$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$reference
##         key doi-asserted-by first-page                        DOI volume
## 1   336_CR1       publisher         77  10.1007/s10822-011-9487-0     26
## 2   336_CR2       publisher       2174          10.1021/ci2001428     26
## 3   336_CR3       publisher       8732          10.1021/ja902302h    131
## 4   336_CR4       publisher        156 10.2174/157340908785747410      4
## 5   336_CR5       publisher        322 10.2174/157340908786786010      4
## 6   336_CR6       publisher         47          10.1021/ci600338x     47
## 7   336_CR7       publisher        366     10.1002/minf.201000019     29
## 8   336_CR8       publisher       4443          10.1021/jo8001276     73
## 9   336_CR9            <NA>       <NA>                       <NA>   <NA>
## 10 336_CR10            <NA>       <NA>                       <NA>   <NA>
## 11 336_CR11       publisher       D255         10.1093/nar/gkp965     38
## 12 336_CR12       publisher        177          10.1021/ci049714+     45
## 13 336_CR13       publisher      D1100         10.1093/nar/gkr777     40
## 14 336_CR14       publisher        347 10.1016/j.cbpa.2010.02.018     14
## 15 336_CR15       publisher        374          10.1021/ci0255782     43
## 16 336_CR16            <NA>       <NA>                       <NA>   <NA>
##              author year
## 1          E Martin 2011
## 2        SR Langdon 2011
## 3           LC Blum 2009
## 4          J Dubois 2008
## 5  JL Medina-Franco 2008
## 6   A Schuffenhauer 2007
## 7         S Langdon 2010
## 8         AH Lipkus 2008
## 9              <NA> <NA>
## 10             <NA> <NA>
## 11           Y Wang 2009
## 12         JJ Irwin 2004
## 13        A Gaulton 2012
## 14        ME Welsch 2010
## 15           P Ertl 2003
## 16             <NA> <NA>
##                                                                                                                                                                                                                                                                  unstructured
## 1                                                                                                                   Martin E, Ertl P, Hunt P, Duca J, Lewis R: Gazing into the crystal ball; the future of computer-aided drug design. J Comp-Aided Mol Des. 2011, 26: 77-79.
## 2                                                                                                                                           Langdon SR, Brown N, Blagg J: Scaffold diversity of exemplified medicinal chemistry space. J Chem Inf Model. 2011, 26: 2174-2185.
## 3                                                                                          Blum LC, Reymond J-C: 970 Million druglike small molecules for virtual screening in the chemical universe database GDB-13. J Am Chem Soc. 2009, 131: 8732-8733. 10.1021/ja902302h.
## 4                                                                                                       Dubois J, Bourg S, Vrain C, Morin-Allory L: Collections of compounds - how to deal with them?. Cur Comp-Aided Drug Des. 2008, 4: 156-168. 10.2174/157340908785747410.
## 5                                                                 Medina-Franco JL, Martinez-Mayorga K, Giulianotti MA, Houghten RA, Pinilla C: Visualization of the chemical space in drug discovery. Cur Comp-Aided Drug Des. 2008, 4: 322-333. 10.2174/157340908786786010.
## 6                                                  Schuffenhauer A, Ertl P, Roggo S, Wetzel S, Koch MA, Waldmann H: The Scaffold Tree - visualization of the scaffold universe by hierarchical scaffold classification. J Chem Inf Model. 2007, 47: 47-58. 10.1021/ci600338x.
## 7                                                                                                          Langdon S, Ertl P, Brown N: Bioisosteric replacement and scaffold hopping in lead generation and optimization. Mol Inf. 2010, 29: 366-385. 10.1002/minf.201000019.
## 8                                                            Lipkus AH, Yuan Q, Lucas KA, Funk SA, Bartelt WF, Schenck RJ, Trippe AJ: Structural diversity of organic chemistry. A scaffold analysis of the CAS Registry. J Org Chem. 2008, 73: 4443-4451. 10.1021/jo8001276.
## 9                                                                                                                                 mib 2010.10, Molinspiration Cheminformatics: \n                    http://www.molinspiration.com\n                    \n                  ,
## 10                                                                                                                Bernhard R: Avalon Cheminformatics Toolkit. \n                    http://sourceforge.net/projects/avalontoolkit/\n                    \n                  ,
## 11                                                                              Wang Y, Bolton E, Dracheva S, Karapetyan K, Shoemaker BA, Suzek TO, Wang J, Xiao J, Zhang J, Bryant SH: An overview of the PubChem BioAssay resource. Nucleic Acids Res. 2009, 38: D255-D266.
## 12                                                                                                                              Irwin JJ, Shoichet BK: ZINC − a free database of commercially available compounds for virtual screening. J Chem Inf Model. 2004, 45: 177-182.
## 13           Gaulton A, Bellis LJ, Bento AP, Chambers J, Davies M, Hersey A, Light Y, McGlinchey S, Michalovich D, Al-Lazikani B, Overington JP: ChEMBL: a large-scale bioactivity database for drug discovery. Nucleic Acids Res. 2012, 40: D1100-D1107. 10.1093/nar/gkr777.
## 14                                                                                                        Welsch ME, Snyder SA, Stockwell BR: Privileged scaffolds for library design and drug discovery. Curr Opin Chem Biol. 2010, 14: 347-361. 10.1016/j.cbpa.2010.02.018.
## 15 Ertl P: Cheminformatics analysis of organic substituents: Identification of the most common substituents, calculation of substituent properties, and automatic identification of drug-like bioisosteric groups. J Chem Inf Comp Sci. 2003, 43: 374-380. 10.1021/ci0255782.
## 16                                                                                                                                                                                                                        TagCrowd: \n                    http://tagcrowd.com
##              journal-title
## 1     J Comp-Aided Mol Des
## 2         J Chem Inf Model
## 3            J Am Chem Soc
## 4  Cur Comp-Aided Drug Des
## 5  Cur Comp-Aided Drug Des
## 6         J Chem Inf Model
## 7                  Mol Inf
## 8               J Org Chem
## 9                     <NA>
## 10                    <NA>
## 11       Nucleic Acids Res
## 12        J Chem Inf Model
## 13       Nucleic Acids Res
## 14     Curr Opin Chem Biol
## 15     J Chem Inf Comp Sci
## 16                    <NA>
## 
## $message$`container-title`
## [1] "Journal of Cheminformatics"
## 
## $message$`original-title`
## list()
## 
## $message$language
## [1] "en"
## 
## $message$link
##                                                                     URL
## 1       http://link.springer.com/content/pdf/10.1186/1758-2946-4-12.pdf
## 2 http://link.springer.com/article/10.1186/1758-2946-4-12/fulltext.html
## 3       http://link.springer.com/content/pdf/10.1186/1758-2946-4-12.pdf
##      content-type content-version intended-application
## 1 application/pdf             vor          text-mining
## 2       text/html             vor          text-mining
## 3 application/pdf             vor  similarity-checking
## 
## $message$deposited
## $message$deposited$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2019    6   24
## 
## $message$deposited$`date-time`
## [1] "2019-06-24T14:22:07Z"
## 
## $message$deposited$timestamp
## [1] 1.561386e+12
## 
## 
## $message$score
## [1] 1
## 
## $message$resource
## $message$resource$primary
## $message$resource$primary$URL
## [1] "https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-4-12"
## 
## 
## 
## $message$subtitle
## list()
## 
## $message$`short-title`
## list()
## 
## $message$issued
## $message$issued$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$`references-count`
## [1] 16
## 
## $message$`journal-issue`
## $message$`journal-issue`$issue
## [1] "1"
## 
## $message$`journal-issue`$`published-print`
## $message$`journal-issue`$`published-print`$`date-parts`
##      [,1] [,2]
## [1,] 2012   12
## 
## 
## 
## $message$`alternative-id`
## [1] "336"
## 
## $message$URL
## [1] "http://dx.doi.org/10.1186/1758-2946-4-12"
## 
## $message$relation
## named list()
## 
## $message$ISSN
## [1] "1758-2946"
## 
## $message$`issn-type`
##       value       type
## 1 1758-2946 electronic
## 
## $message$subject
## [1] "Library and Information Sciences"           
## [2] "Computer Graphics and Computer-Aided Design"
## [3] "Physical and Theoretical Chemistry"         
## [4] "Computer Science Applications"              
## 
## $message$published
## $message$published$`date-parts`
##      [,1] [,2] [,3]
## [1,] 2012    7    6
## 
## 
## $message$`article-number`
## [1] "12"
```

### 2. CrossRef API call with a Loop

#### Setup API parameters


```r
base_url <- "https://api.crossref.org/works/"
email <- "your_email@ua.edu" #Change this to your email
mailto <- "?mailto="
doi <- "10.1186/1758-2946-4-12" #example
```

#### Create a List of DOIs


```r
#Create List of DOIs

doi_list <- list('10.1021/acsomega.1c03250',                          
             '10.1021/acsomega.1c05512',
             '10.1021/acsomega.8b01647',
             '10.1021/acsomega.1c04287',
             '10.1021/acsomega.8b01834')
```

#### Request metadata for each DOI from CrossRef API and save to a list


```r
doi_metadata <- list(list()) # a list of lists is used to hold the data from the 5 DOIs
i <- 1
for (doi in doi_list){
  doi_metadata[[i]] <-fromJSON(rawToChar(GET(paste(base_url, doi, mailto, email, sep=""))$content), flatten = TRUE)
  i <- i+1
  Sys.sleep(1)  # important to add a delay between API calls
}
# doi_metadata ## not shown here as it is long.
```

Let's select some specific data


```r
# Get Article titles
for (item in 1:length(doi_metadata)){
  print(doi_metadata[[item]]$message$title)
}
```

```
## [1] "Navigating into the Chemical Space of Monoamine Oxidase Inhibitors by Artificial Intelligence and Cheminformatics Approach"
## [1] "Impact of Artificial Intelligence on Compound Discovery, Design, and Synthesis"
## [1] "How Precise Are Our Quantitative Structure–Activity Relationship Derived Predictions for New Query Chemicals?"
## [1] "Applying Neuromorphic Computing Simulation in Band Gap Prediction and Chemical Reaction Classification"
## [1] "QSPR Modeling of the Refractive Index for Diverse Polymers Using 2D Descriptors"
```


```r
#Get Author affiliations for each Article
for (item in 1:length(doi_metadata)){
  for (au in 1:length(doi_metadata[[item]]$message$author)){
    print(doi_metadata[[item]]$message$author$affiliation[[1]]$name)
  }
}
```

```
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Pharmaceutical Chemistry and Analysis, Amrita School of Pharmacy, Amrita Vishwa Vidyapeetham, AIMS Health Sciences Campus, Kochi 682041, India"
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Department of Life Science Informatics and Data Science, B-IT, LIMES Program Unit Chemical Biology and Medicinal Chemistry, Rheinische Friedrich-Wilhelms-Universität, Friedrich-Hirzebruch-Allee 6, D-53115 Bonn, Germany"
## [2] "Data Science and AI, Imaging and Data Analytics, Clinical Pharmacology & Safety Sciences, R&D, AstraZeneca, SE-431 83 Gothenburg, Sweden"                                                                                  
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Drug Theoretics and Cheminformatics Laboratory, Department of Pharmaceutical Technology, Jadavpur University, Kolkata 700 032, India"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Chemical and Biomolecular Engineering, The Ohio State University, Columbus, Ohio 43210, United States"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
## [1] "Department of Pharmacoinformatics, National Institute of Pharmaceutical Educational and Research (NIPER), Chunilal Bhawan, 168, Manikata Main Road, 700054 Kolkata, India"
```

### 3. Crossref API call for journal information

#### Setup API parameters


```r
jbase_url <- "https://api.crossref.org/journals/" # the base url for api calls
email <- "your_email@ua.edu" # Change this to be your email
mailto <- "?mailto="
issn <- "1471-2105"  # issn for the journal BMC Bioinformatics
```

#### Request journal data from crossref API


```r
jour_data <- fromJSON(rawToChar(GET(paste(jbase_url, issn, mailto, email, sep=""))$content), flatten = TRUE) 
jour_data
```

```
## $status
## [1] "ok"
## 
## $`message-type`
## [1] "journal"
## 
## $`message-version`
## [1] "1.0.0"
## 
## $message
## $message$`last-status-check-time`
## [1] 1.681117e+12
## 
## $message$counts
## $message$counts$`current-dois`
## [1] 1347
## 
## $message$counts$`backfile-dois`
## [1] 10498
## 
## $message$counts$`total-dois`
## [1] 11845
## 
## 
## $message$breakdowns
## $message$breakdowns$`dois-by-issued-year`
##       [,1] [,2]
##  [1,] 2010  861
##  [2,] 2019  762
##  [3,] 2008  745
##  [4,] 2009  729
##  [5,] 2011  722
##  [6,] 2006  633
##  [7,] 2021  622
##  [8,] 2014  619
##  [9,] 2007  613
## [10,] 2012  609
## [11,] 2013  607
## [12,] 2015  603
## [13,] 2020  585
## [14,] 2017  585
## [15,] 2022  582
## [16,] 2016  550
## [17,] 2018  536
## [18,] 2005  414
## [19,] 2004  209
## [20,] 2023  143
## [21,] 2003   66
## [22,] 2002   40
## [23,] 2001    9
## [24,] 2000    1
## 
## 
## $message$publisher
## [1] "Springer (Biomed Central Ltd.)"
## 
## $message$coverage
## $message$coverage$`affiliations-current`
## [1] 0
## 
## $message$coverage$`similarity-checking-current`
## [1] 1
## 
## $message$coverage$`descriptions-current`
## [1] 0
## 
## $message$coverage$`ror-ids-current`
## [1] 0
## 
## $message$coverage$`funders-backfile`
## [1] 0.1704134
## 
## $message$coverage$`licenses-backfile`
## [1] 0.561726
## 
## $message$coverage$`funders-current`
## [1] 0.6911656
## 
## $message$coverage$`affiliations-backfile`
## [1] 0
## 
## $message$coverage$`resource-links-backfile`
## [1] 0.5611545
## 
## $message$coverage$`orcids-backfile`
## [1] 0.1299295
## 
## $message$coverage$`update-policies-current`
## [1] 1
## 
## $message$coverage$`ror-ids-backfile`
## [1] 0
## 
## $message$coverage$`orcids-current`
## [1] 0.4632517
## 
## $message$coverage$`similarity-checking-backfile`
## [1] 0.9561821
## 
## $message$coverage$`references-backfile`
## [1] 0.9400838
## 
## $message$coverage$`descriptions-backfile`
## [1] 0
## 
## $message$coverage$`award-numbers-backfile`
## [1] 0.1554582
## 
## $message$coverage$`update-policies-backfile`
## [1] 0.660983
## 
## $message$coverage$`licenses-current`
## [1] 1
## 
## $message$coverage$`award-numbers-current`
## [1] 0.610245
## 
## $message$coverage$`abstracts-backfile`
## [1] 0.3347304
## 
## $message$coverage$`resource-links-current`
## [1] 1
## 
## $message$coverage$`abstracts-current`
## [1] 0.9784707
## 
## $message$coverage$`references-current`
## [1] 0.9985152
## 
## 
## $message$title
## [1] "BMC Bioinformatics"
## 
## $message$subjects
##   ASJC                          name
## 1 2604           Applied Mathematics
## 2 1706 Computer Science Applications
## 3 1312             Molecular Biology
## 4 1303                  Biochemistry
## 5 1315            Structural Biology
## 
## $message$`coverage-type`
## $message$`coverage-type`$all
## $message$`coverage-type`$all$`last-status-check-time`
## [1] 1.681117e+12
## 
## $message$`coverage-type`$all$affiliations
## [1] 0
## 
## $message$`coverage-type`$all$abstracts
## [1] 0.4079358
## 
## $message$`coverage-type`$all$orcids
## [1] 0.1678345
## 
## $message$`coverage-type`$all$licenses
## [1] 0.6115661
## 
## $message$`coverage-type`$all$references
## [1] 0.9467286
## 
## $message$`coverage-type`$all$funders
## [1] 0.2296328
## 
## $message$`coverage-type`$all$`similarity-checking`
## [1] 0.961165
## 
## $message$`coverage-type`$all$`award-numbers`
## [1] 0.207176
## 
## $message$`coverage-type`$all$`ror-ids`
## [1] 0
## 
## $message$`coverage-type`$all$`update-policies`
## [1] 0.6995357
## 
## $message$`coverage-type`$all$`resource-links`
## [1] 0.6110595
## 
## $message$`coverage-type`$all$descriptions
## [1] 0
## 
## 
## $message$`coverage-type`$backfile
## $message$`coverage-type`$backfile$`last-status-check-time`
## [1] 1.681117e+12
## 
## $message$`coverage-type`$backfile$affiliations
## [1] 0
## 
## $message$`coverage-type`$backfile$abstracts
## [1] 0.3347304
## 
## $message$`coverage-type`$backfile$orcids
## [1] 0.1299295
## 
## $message$`coverage-type`$backfile$licenses
## [1] 0.561726
## 
## $message$`coverage-type`$backfile$references
## [1] 0.9400838
## 
## $message$`coverage-type`$backfile$funders
## [1] 0.1704134
## 
## $message$`coverage-type`$backfile$`similarity-checking`
## [1] 0.9561821
## 
## $message$`coverage-type`$backfile$`award-numbers`
## [1] 0.1554582
## 
## $message$`coverage-type`$backfile$`ror-ids`
## [1] 0
## 
## $message$`coverage-type`$backfile$`update-policies`
## [1] 0.660983
## 
## $message$`coverage-type`$backfile$`resource-links`
## [1] 0.5611545
## 
## $message$`coverage-type`$backfile$descriptions
## [1] 0
## 
## 
## $message$`coverage-type`$current
## $message$`coverage-type`$current$`last-status-check-time`
## [1] 1.681117e+12
## 
## $message$`coverage-type`$current$affiliations
## [1] 0
## 
## $message$`coverage-type`$current$abstracts
## [1] 0.9784707
## 
## $message$`coverage-type`$current$orcids
## [1] 0.4632517
## 
## $message$`coverage-type`$current$licenses
## [1] 1
## 
## $message$`coverage-type`$current$references
## [1] 0.9985152
## 
## $message$`coverage-type`$current$funders
## [1] 0.6911656
## 
## $message$`coverage-type`$current$`similarity-checking`
## [1] 1
## 
## $message$`coverage-type`$current$`award-numbers`
## [1] 0.610245
## 
## $message$`coverage-type`$current$`ror-ids`
## [1] 0
## 
## $message$`coverage-type`$current$`update-policies`
## [1] 1
## 
## $message$`coverage-type`$current$`resource-links`
## [1] 1
## 
## $message$`coverage-type`$current$descriptions
## [1] 0
## 
## 
## 
## $message$flags
## $message$flags$`deposits-abstracts-current`
## [1] TRUE
## 
## $message$flags$`deposits-orcids-current`
## [1] TRUE
## 
## $message$flags$deposits
## [1] TRUE
## 
## $message$flags$`deposits-affiliations-backfile`
## [1] FALSE
## 
## $message$flags$`deposits-update-policies-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-similarity-checking-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-award-numbers-current`
## [1] TRUE
## 
## $message$flags$`deposits-resource-links-current`
## [1] TRUE
## 
## $message$flags$`deposits-ror-ids-current`
## [1] FALSE
## 
## $message$flags$`deposits-articles`
## [1] TRUE
## 
## $message$flags$`deposits-affiliations-current`
## [1] FALSE
## 
## $message$flags$`deposits-funders-current`
## [1] TRUE
## 
## $message$flags$`deposits-references-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-ror-ids-backfile`
## [1] FALSE
## 
## $message$flags$`deposits-abstracts-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-licenses-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-award-numbers-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-descriptions-current`
## [1] FALSE
## 
## $message$flags$`deposits-references-current`
## [1] TRUE
## 
## $message$flags$`deposits-resource-links-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-descriptions-backfile`
## [1] FALSE
## 
## $message$flags$`deposits-orcids-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-funders-backfile`
## [1] TRUE
## 
## $message$flags$`deposits-update-policies-current`
## [1] TRUE
## 
## $message$flags$`deposits-similarity-checking-current`
## [1] TRUE
## 
## $message$flags$`deposits-licenses-current`
## [1] TRUE
## 
## 
## $message$ISSN
## [1] "1471-2105" "1471-2105"
## 
## $message$`issn-type`
##       value       type
## 1 1471-2105      print
## 2 1471-2105 electronic
```

### 4. Crossref API - Get article DOIs for a journal

#### Setup API parameters


```r
jbase_url <- "https://api.crossref.org/journals/" # the base url for api calls
email <- "your_email@ua.edu" # Change this to be your email
mailto = "&mailto="
issn <- "1471-2105"  # issn for the journal BMC Bioinformatics
journal_works2014 <- "/works?filter=from-pub-date:2014,until-pub-date:2014&select=DOI" # query to get DOIs for 2014
```

#### Request DOI data from crossref API


```r
doi_data = fromJSON(rawToChar(GET(paste(jbase_url, issn, journal_works2014, mailto, email, sep=""))$content), flatten = TRUE)
doi_data
```

```
## $status
## [1] "ok"
## 
## $`message-type`
## [1] "work-list"
## 
## $`message-version`
## [1] "1.0.0"
## 
## $message
## $message$facets
## named list()
## 
## $message$`total-results`
## [1] 619
## 
## $message$items
##                             DOI
## 1   10.1186/1471-2105-15-s10-p5
## 2      10.1186/1471-2105-15-166
## 3       10.1186/1471-2105-15-83
## 4  10.1186/1471-2105-15-s10-p28
## 5   10.1186/1471-2105-15-s10-p6
## 6       10.1186/1471-2105-15-16
## 7   10.1186/1471-2105-15-s11-i1
## 8      10.1186/1471-2105-15-276
## 9      10.1186/1471-2105-15-254
## 10     10.1186/1471-2105-15-266
## 11     10.1186/1471-2105-15-337
## 12      10.1186/1471-2105-15-33
## 13     10.1186/1471-2105-15-187
## 14 10.1186/1471-2105-15-s16-s13
## 15     10.1186/1471-2105-15-137
## 16      10.1186/1471-2105-15-63
## 17     10.1186/1471-2105-15-318
## 18   10.1186/1471-2105-15-s1-s2
## 19    10.1186/s12859-014-0358-2
## 20 10.1186/1471-2105-15-s10-p35
## 
## $message$`items-per-page`
## [1] 20
## 
## $message$query
## $message$query$`start-index`
## [1] 0
## 
## $message$query$`search-terms`
## NULL
```

By default, 20 results are displayed. Crossref allows up to 1000 returned results using the rows parameter. To get all 619 results, we can increase the number of returned rows.


```r
rows <- "&rows=700"
doi_data_all <- fromJSON(rawToChar(GET(paste(jbase_url, issn, journal_works2014, rows, mailto, email, sep=""))$content), flatten = TRUE)
```

#### Extract DOIs


```r
dois_list = list()
for (i in doi_data_all$message$items){
  dois_list <- append(x = dois_list, doi_data_all$message$items$DOI)
}
length(dois_list)
```

```
## [1] 619
```


```r
#display the first 20
print (dois_list[0:20])
```

```
## [[1]]
## [1] "10.1186/1471-2105-15-s7-s7"
## 
## [[2]]
## [1] "10.1186/1471-2105-15-84"
## 
## [[3]]
## [1] "10.1186/s12859-014-0411-1"
## 
## [[4]]
## [1] "10.1186/1471-2105-15-177"
## 
## [[5]]
## [1] "10.1186/1471-2105-15-s10-p24"
## 
## [[6]]
## [1] "10.1186/1471-2105-15-s1-s2"
## 
## [[7]]
## [1] "10.1186/1471-2105-15-s10-p32"
## 
## [[8]]
## [1] "10.1186/1471-2105-15-193"
## 
## [[9]]
## [1] "10.1186/1471-2105-15-192"
## 
## [[10]]
## [1] "10.1186/1471-2105-15-s11-i1"
## 
## [[11]]
## [1] "10.1186/1471-2105-15-88"
## 
## [[12]]
## [1] "10.1186/1471-2105-15-331"
## 
## [[13]]
## [1] "10.1186/1471-2105-15-s11-s10"
## 
## [[14]]
## [1] "10.1186/1471-2105-15-s1-s8"
## 
## [[15]]
## [1] "10.1186/1471-2105-15-s14-s1"
## 
## [[16]]
## [1] "10.1186/1471-2105-15-s10-p33"
## 
## [[17]]
## [1] "10.1186/1471-2105-15-s10-p35"
## 
## [[18]]
## [1] "10.1186/s12859-014-0358-2"
## 
## [[19]]
## [1] "10.1186/1471-2105-15-s10-p6"
## 
## [[20]]
## [1] "10.1186/1471-2105-15-115"
```

What if we have more than 1000 results in a single query?

For example, if we wanted the DOIs from BMC Bioinformatics for years 2014 through 2016?


```r
jbase_url <- "https://api.crossref.org/journals/" # the base url for api calls
email <- "your_email@ua.edu" # Change this to be your email
mailto <- "&mailto="
issn <- "1471-2105"  # issn for the journal BMC Bioinformatics
journal_works2014_2016 <- "/works?filter=from-pub-date:2014,until-pub-date:2016&select=DOI" # query to get DOIs for 2014-2016
doi_data2 <- fromJSON(paste(jbase_url, issn, journal_works2014_2016, mailto, email, sep=""), flatten = TRUE)
doi_data2
```

```
## $status
## [1] "ok"
## 
## $`message-type`
## [1] "work-list"
## 
## $`message-version`
## [1] "1.0.0"
## 
## $message
## $message$facets
## named list()
## 
## $message$`total-results`
## [1] 1772
## 
## $message$items
##                             DOI
## 1     10.1186/s12859-015-0538-8
## 2   10.1186/1471-2105-16-s18-s5
## 3     10.1186/s12859-016-1086-6
## 4     10.1186/s12859-016-1343-8
## 5    10.1186/1471-2105-15-s7-s7
## 6       10.1186/1471-2105-15-84
## 7     10.1186/s12859-014-0411-1
## 8      10.1186/1471-2105-15-177
## 9  10.1186/1471-2105-16-s15-p13
## 10    10.1186/s12859-015-0699-5
## 11 10.1186/1471-2105-15-s10-p24
## 12    10.1186/s12859-016-1297-x
## 13    10.1186/s12859-015-0791-x
## 14   10.1186/1471-2105-15-s1-s2
## 15  10.1186/1471-2105-16-s10-s1
## 16    10.1186/s12859-015-0628-7
## 17    10.1186/s12859-015-0834-3
## 18 10.1186/1471-2105-15-s10-p32
## 19    10.1186/s12859-016-1129-z
## 20     10.1186/1471-2105-15-193
## 
## $message$`items-per-page`
## [1] 20
## 
## $message$query
## $message$query$`start-index`
## [1] 0
## 
## $message$query$`search-terms`
## NULL
```

Here we see that the total results is over 1000 (total-results: 1772). An additional parameter that we can use with crossref API is called "offset". The offset option allows us to select sets of records and define a starting position (e.g., the first 1000, and then the second set of up to 1000.)


```r
doi_list2 <- list() #declare a list
rows <- "&rows=1000"

temp <- fromJSON(paste(jbase_url, issn, journal_works2014_2016, mailto, email, sep=""), flatten = TRUE)
numResults<- temp$message$`total-results`
Sys.sleep(1)

end <- as.integer(numResults/1000)+1

for (n in 0:end){ # list(range(int(numberOfResults/1000)+1)) = [0,1]
  query <- fromJSON(paste(jbase_url, issn, journal_works2014_2016, rows, "&offset=", as.character(1000*n), mailto, email, sep=""), flatten = TRUE)
  Sys.sleep(1)
  for (doi in query$message$items){
    doi_list2 <- append(x = doi_list2, query$message$items$DOI)
  }
}
```


```r
length(doi_list2)
```

```
## [1] 1772
```


```r
#how results 1000 through 1020
print(doi_list2[1000:1020])
```

```
## [[1]]
## [1] "10.1186/s12859-016-1012-y"
## 
## [[2]]
## [1] "10.1186/s12859-016-1147-x"
## 
## [[3]]
## [1] "10.1186/s12859-016-1386-x"
## 
## [[4]]
## [1] "10.1186/1471-2105-15-s10-p13"
## 
## [[5]]
## [1] "10.1186/1471-2105-16-s15-p7"
## 
## [[6]]
## [1] "10.1186/s12859-014-0361-7"
## 
## [[7]]
## [1] "10.1186/s12859-014-0429-4"
## 
## [[8]]
## [1] "10.1186/1471-2105-15-29"
## 
## [[9]]
## [1] "10.1186/s12859-016-1232-1"
## 
## [[10]]
## [1] "10.1186/s12859-016-1126-2"
## 
## [[11]]
## [1] "10.1186/1471-2105-16-s4-s8"
## 
## [[12]]
## [1] "10.1186/s12859-016-1102-x"
## 
## [[13]]
## [1] "10.1186/1471-2105-15-238"
## 
## [[14]]
## [1] "10.1186/s12859-016-1236-x"
## 
## [[15]]
## [1] "10.1186/s12859-016-1317-x"
## 
## [[16]]
## [1] "10.1186/1471-2105-16-s19-s8"
## 
## [[17]]
## [1] "10.1186/s12859-014-0428-5"
## 
## [[18]]
## [1] "10.1186/1471-2105-15-s10-p8"
## 
## [[19]]
## [1] "10.1186/1471-2105-15-48"
## 
## [[20]]
## [1] "10.1186/s12859-016-1342-9"
## 
## [[21]]
## [1] "10.1186/s12859-015-0746-2"
```
